version: 2
updates:
  # Updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  # Updates for python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # Updates for git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  # Updates for ruby gems
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  # Updates for maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
